### ISSUE TITLE
Provide the basis for sending and receiving SMS with Twilio

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hrt-bus-api#4]
Detroit seems to have a good model: http://www.detroitmi.gov/Portals/0/docs/deptoftransportation/pdfs/TextMyBusBroch2_5_3.pdf

**Comment by stanzheng** [comment]
closing this issue with age. we have a version of this with https://github.com/code4hr/hrt-bus-text-my-bus  that uses twilio.
