### ISSUE TITLE
replace api URL in code to api.hrtb.us

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hrt-bus-api#54]
change from lit-inlet-3610.herokuapp.com to api.hrtb.us so we can standarize on a common api url for this and any future apps we may want to build on our awesome bus api.

api.hrtb.us is just a DNS CNAME to lit-inlet-3610.herokuapp.com

**Comment by stanzheng** [comment]
new route is  

api.hrtb.us/api/
