### ISSUE TITLE
Distribute 0.6.31 is not compatible with most out-of-the-box python2 installations.

### ISSUE THREAD

**Issue by billjordan** [Code4HR/hrt-bus-api#72]
The distribute package available through pip is on version 0.7.3 which doesn't seem to be backwards compatible with 0.6.31. I tested upgrading distribute to 0.7.3 and it worked out of the box on Debian, Ubuntu, CentOS and Windows 10. Wtih 0.6.31 it only worked on Ubuntu.

Since it is easier to upgrade than downgrade a package with pip, I think distribute should be upgraded to version 0.7.3.

**Comment by stanzheng** [comment]
closed by merge in 

https://github.com/Code4HR/hrt-bus-api/commit/973391d21bc261257e36b1eafd70d18675be2029
