### ISSUE TITLE
Trip planning 

### ISSUE THREAD

**Issue by stanzheng** [Code4HR/hrt-bus-api#76]
which bus to take to route to the specific bus

**Comment by stanzheng** [comment]
not on roadmap to support this in api

**Comment by BenjaminCMiller** [comment]
Hi Stanley, wrong Ben. Have a great weekend!

**Comment by stanzheng** [comment]
hi @BenjaminCMiller it looks like you added yourself to the "watchers" of the project voluntarily at some point. you can remove yourself by clicking unwatching. (see at this link https://github.com/Code4HR/hrt-bus-api/watchers) 

I was doing some cleaning up on some issues on the project.
