### ISSUE TITLE
Add an endpoint that accepts a list of stop ids and returns stops and bus schedule data

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-api#80]
For example, something like `GET /api/stops?id=234,114,13` should return stop and bus information related to stops 234, 114, and 13.  Response should look similar to the output created by the `/api/stops/near/<lat>/<lng>/`
##

**Comment by bschoenfeld** [comment]
http://lit-inlet-3610.herokuapp.com/api/stops/id/1001/1002/

Is that close to what you are looking for?

**Comment by wbprice** [comment]
Close, but I also need bus timing info for each of those stops to come back in the same request.

**Comment by stanzheng** [comment]
its been implemented in v2_api

https://github.com/Code4HR/hrt-bus-api/wiki/RESTful-API#stop-times-1
